import { StoreShell } from "@/components/StoreShell";
import { trpc } from "@/lib/trpc";
import { MessageCircle, Phone, ShoppingBag } from "lucide-react";
import { Link } from "wouter";

export default function Contact() {
  const { data: settings } = trpc.catalog.settings.useQuery();
  const phone = settings?.supportPhone || "773207714";
  const secondary = settings?.secondaryPhone || "713861074";
  const whatsapp = settings?.whatsappNumber || "967773207714";
  return <StoreShell><main className="container py-10 sm:py-14"><section className="rounded-[2rem] bg-[#4a2907] px-6 py-12 text-center text-[#f6e3b7]"><p className="text-xs font-bold text-[#f6cd70]">نحن هنا لخدمتك</p><h1 className="mt-2 font-display text-5xl text-white">تواصل مع ماجد سراج</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-8 text-[#efd8a6]">للطلبات السريعة والاستفسارات وطلبات الجملة، تواصل معنا مباشرة عبر واتساب أو الهاتف.</p></section><section className="mx-auto mt-8 grid max-w-4xl gap-4 md:grid-cols-3"><a href={`https://wa.me/${whatsapp.replace(/\D/g, "")}`} target="_blank" rel="noreferrer" className="rounded-3xl border border-[#ead8b3] bg-white p-6 text-center shadow-sm transition-transform hover:-translate-y-1"><MessageCircle className="mx-auto text-[#198754]" size={28} /><h2 className="mt-3 font-bold text-[#5e3508]">واتساب الطلبات</h2><p className="mt-2 text-sm text-[#806743]">{phone}</p></a><a href={`tel:${phone}`} className="rounded-3xl border border-[#ead8b3] bg-white p-6 text-center shadow-sm transition-transform hover:-translate-y-1"><Phone className="mx-auto text-[#a45c08]" size={28} /><h2 className="mt-3 font-bold text-[#5e3508]">الهاتف</h2><p className="mt-2 text-sm text-[#806743]">{phone}</p></a><a href={`tel:${secondary}`} className="rounded-3xl border border-[#ead8b3] bg-white p-6 text-center shadow-sm transition-transform hover:-translate-y-1"><Phone className="mx-auto text-[#a45c08]" size={28} /><h2 className="mt-3 font-bold text-[#5e3508]">رقم إضافي</h2><p className="mt-2 text-sm text-[#806743]">{secondary}</p></a></section><section className="mx-auto mt-10 max-w-4xl rounded-3xl bg-[#f7ead3] p-7 sm:p-9"><div className="flex flex-wrap items-center justify-between gap-5"><div><h2 className="font-display text-4xl text-[#5e3508]">هل جهزت طلبك؟</h2><p className="mt-2 text-sm leading-7 text-[#765a35]">استخدم السلة لتضمين المنتجات والأوزان والكميات تلقائيًا في رسالة واتساب.</p></div><Link href="/shop" className="inline-flex items-center gap-2 rounded-xl bg-[#b66d08] px-5 py-3 text-sm font-bold text-white hover:bg-[#925404]"><ShoppingBag size={17} />تصفح المتجر</Link></div></section></main></StoreShell>;
}
