import { ProductCard } from "@/components/ProductCard";
import { StoreShell } from "@/components/StoreShell";
import { StoreImage } from "@/components/StoreImage";
import { trpc } from "@/lib/trpc";
import { Link } from "wouter";
import { ArrowLeft, BookOpen, Check, Droplets, MessageCircle, ShieldCheck, Sparkles } from "lucide-react";

export default function Home() {
  const { data: products = [], isLoading } = trpc.catalog.list.useQuery();
  const featured = products.filter(product => product.isFeatured).slice(0, 3);
  return <StoreShell>
    <main>
      <section className="golden-grid overflow-hidden bg-[#4a2907] text-white">
        <div className="container grid items-center gap-10 py-12 sm:py-16 lg:grid-cols-[1fr_.84fr] lg:py-20">
          <div className="rise-in relative z-10"><span className="inline-flex items-center gap-2 rounded-full border border-[#f6cd70]/35 bg-[#f6cd70]/10 px-4 py-2 text-xs text-[#f7dc98]"><Sparkles size={14} />مختارات عسل بلدي للجملة والتجزئة</span><h1 className="mt-5 max-w-2xl font-display text-5xl font-bold leading-[1.15] text-[#fff3d6] sm:text-6xl">طبيعة العسل…<br /><span className="text-[#f3c65c]">بذوق ماجد سراج</span></h1><p className="mt-5 max-w-xl text-sm leading-8 text-[#f1d8a1] sm:text-base">مجموعة مختارة من العسل البلدي، تُقدّم في عبوات متعددة الأوزان، مع تجربة طلب مباشرة وسهلة من خلال واتساب.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/shop" className="inline-flex items-center gap-2 rounded-xl bg-[#f6cd70] px-5 py-3 text-sm font-bold text-[#4a2907] shadow-lg transition-transform duration-200 hover:-translate-y-0.5 active:scale-[.97]">تسوّق الآن <ArrowLeft size={17} /></Link><Link href="/about" className="rounded-xl border border-[#f6cd70]/45 px-5 py-3 text-sm font-bold text-[#f9e8c4] transition-colors hover:bg-white/10">تعرف إلى ماجد سراج</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-xs text-[#efd9aa]"><span className="inline-flex items-center gap-2"><Check size={15} className="text-[#f6cd70]" />طلب مباشر عبر واتساب</span><span className="inline-flex items-center gap-2"><Check size={15} className="text-[#f6cd70]" />أوزان تناسبك</span><span className="inline-flex items-center gap-2"><Check size={15} className="text-[#f6cd70]" />جملة وتجزئة</span></div></div>
          <div className="rise-in relative mx-auto w-full max-w-md [animation-delay:90ms]"><div className="absolute -inset-5 rounded-full bg-[#d5901c]/25 blur-3xl"></div><div className="relative overflow-hidden rounded-[2rem] border border-[#f8d783]/25 bg-[#7a4912] p-3 honey-glow"><StoreImage src="/manus-storage/majid-siraj-honey-identity_885d8b5c.png" alt="منتجات ماجد سراج من العسل البلدي" loading="eager" className="aspect-square w-full rounded-[1.45rem] object-cover" /><div className="absolute bottom-7 left-7 right-7 rounded-2xl border border-white/20 bg-[#321a04]/75 px-4 py-3 backdrop-blur"><p className="font-display text-2xl text-[#f7d477]">ماجد سراج</p><p className="text-xs text-[#f5deac]">جميع أنواع العسل البلدي</p></div></div></div>
        </div>
      </section>

      <section className="container py-12 sm:py-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-[#b66d08]">الأكثر طلبًا</p><h2 className="mt-2 font-display text-4xl font-bold text-[#5e3508]">مختارات المتجر</h2></div><Link href="/shop" className="inline-flex items-center gap-1 text-sm font-bold text-[#925404]">عرض جميع الأنواع <ArrowLeft size={16} /></Link></div>{isLoading ? <div className="mt-8 grid gap-5 md:grid-cols-3">{[1,2,3].map(item => <div key={item} className="h-96 animate-pulse rounded-[1.6rem] bg-[#f1e5cf]" />)}</div> : <div className="mt-8 grid gap-5 md:grid-cols-3">{featured.map((product, index) => <ProductCard key={product.id} product={product} priority={index === 0} />)}</div>}</section>

      <section className="border-y border-[#ead7ad] bg-[#f7ead3]"><div className="container grid gap-5 py-10 sm:grid-cols-3"><div className="rounded-2xl bg-white/65 p-5"><ShieldCheck className="text-[#a45c08]" /><h3 className="mt-3 font-bold text-[#5e3508]">متجر واضح</h3><p className="mt-2 text-xs leading-6 text-[#806743]">الأسعار والأوزان تظهر قبل إنشاء الطلب، لتراجع كل التفاصيل براحتك.</p></div><div className="rounded-2xl bg-white/65 p-5"><Droplets className="text-[#a45c08]" /><h3 className="mt-3 font-bold text-[#5e3508]">تنوع يرضي ذوقك</h3><p className="mt-2 text-xs leading-6 text-[#806743]">خيارات عسل بلدي وأحجام مختلفة للمنزل والضيافة والطلبات الكبيرة.</p></div><div className="rounded-2xl bg-white/65 p-5"><MessageCircle className="text-[#a45c08]" /><h3 className="mt-3 font-bold text-[#5e3508]">الطلب عبر واتساب</h3><p className="mt-2 text-xs leading-6 text-[#806743]">يحفظ المتجر طلبك ثم يفتح واتساب برسالة منسقة لمتابعته مباشرة.</p></div></div></section>

      <section className="container py-12 sm:py-16"><div className="rounded-[2rem] border border-[#e2c787] bg-[#fff8e8] p-7 sm:p-9"><div className="grid items-center gap-6 md:grid-cols-[1fr_auto]"><div><p className="inline-flex items-center gap-2 text-xs font-bold text-[#a45c08]"><BookOpen size={15} />دليل العسل</p><h2 className="mt-2 font-display text-4xl text-[#5e3508]">اعرف أكثر قبل أن تختار</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-[#765a35]">اقرأ عن تنوع الأنواع، أسلوب الحفظ، وأفكار التقديم، مع إجابات سريعة لأكثر الأسئلة شيوعًا.</p></div><Link href="/knowledge" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#5e3508] px-5 py-3 text-sm font-bold text-[#f6cd70]">استكشف الدليل <ArrowLeft size={16} /></Link></div></div></section>

      <section className="container grid items-center gap-8 py-12 sm:py-16 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-[1.8rem] bg-[#5e3508] p-7 text-[#f6e3b7]"><p className="text-xs font-bold text-[#f6cd70]">من المصدر إلى مائدتك</p><h2 className="mt-2 font-display text-4xl text-white">تجربة طلب بسيطة<br />ومتابعة شخصية</h2><Link href="/contact" className="mt-6 inline-flex rounded-xl border border-[#f6cd70]/50 px-4 py-3 text-sm font-bold text-[#f6cd70] hover:bg-white/10">تواصل مع ماجد سراج</Link></div><div><p className="text-sm leading-8 text-[#775a35]">في «ماجد سراج» نرتب لك تجربة تصفح هادئة: اختر نوع العسل، حدّد الوزن والكمية، ثم أرسل الطلب مكتمل البيانات عبر واتساب. هذه الطريقة تمنحك مساحة واضحة لطلب التجزئة أو الاستفسار عن طلبات الجملة.</p><Link href="/shop" className="mt-5 inline-flex items-center gap-2 font-bold text-[#a45c08]">ابدأ اختيار العسل <ArrowLeft size={17} /></Link></div></section>
    </main>
  </StoreShell>;
}
