import { StoreImage } from "./StoreImage";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, PackageCheck, Save } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

type Draft = { inventoryCount: number; lowStockThreshold: number };

export default function InventoryManagement() {
  const utils = trpc.useUtils();
  const { data: products = [] } = trpc.admin.products.useQuery();
  const { data: lowStock = [] } = trpc.admin.lowStock.useQuery();
  const [drafts, setDrafts] = useState<Record<number, Draft>>({});
  useEffect(() => setDrafts(Object.fromEntries(products.map(product => [product.id, { inventoryCount: product.inventoryCount, lowStockThreshold: product.lowStockThreshold }]))), [products]);
  const update = trpc.admin.updateInventory.useMutation({ onSuccess() { utils.admin.products.invalidate(); utils.admin.lowStock.invalidate(); utils.admin.stats.invalidate(); utils.catalog.list.invalidate(); toast.success("تم حفظ بيانات المخزون"); }, onError(error) { toast.error(error.message); } });
  return <section className="mt-7"><div className="rounded-3xl border border-[#ead8b3] bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-[#5e3508]"><PackageCheck size={22} /><h2 className="font-display text-3xl">إدارة المخزون</h2></div><p className="mt-2 text-xs leading-6 text-[#806743]">يُخصم عدد الوحدات تلقائيًا عند تسجيل طلب عبر المتجر. عدّل الكمية بعد التوريد أو عند إلغاء طلب.</p></div><span className={`inline-flex items-center gap-2 rounded-xl px-3 py-2 text-xs font-bold ${lowStock.length ? "bg-[#fde8e3] text-[#a83a23]" : "bg-[#e5f3df] text-[#37711d]"}`}><AlertTriangle size={15} />{lowStock.length ? `${lowStock.length} منتجات تحتاج متابعة` : "المخزون ضمن الحدود"}</span></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-180 text-right text-xs"><thead className="bg-[#f9edda] text-[#6c4a1d]"><tr><th className="p-3">المنتج</th><th className="p-3">الكمية المتاحة</th><th className="p-3">حد التنبيه</th><th className="p-3">الحالة</th><th className="p-3">حفظ</th></tr></thead><tbody>{products.map(product => { const draft = drafts[product.id] || { inventoryCount: product.inventoryCount, lowStockThreshold: product.lowStockThreshold }; const out = draft.inventoryCount <= 0; const low = !out && draft.inventoryCount <= draft.lowStockThreshold; return <tr key={product.id} className="border-t border-[#f1e5cf]"><td className="p-3"><div className="flex items-center gap-3"><StoreImage src={product.primaryImage} alt="" className="h-9 w-9 rounded-lg object-cover" /><span className="font-bold text-[#5e3508]">{product.name}</span></div></td><td className="p-3"><input type="number" min="0" value={draft.inventoryCount} onChange={event => setDrafts(current => ({ ...current, [product.id]: { ...draft, inventoryCount: Math.max(0, Number(event.target.value)) } }))} className="h-9 w-24 rounded-lg border bg-[#fffdf8] px-2 text-center" /></td><td className="p-3"><input type="number" min="0" value={draft.lowStockThreshold} onChange={event => setDrafts(current => ({ ...current, [product.id]: { ...draft, lowStockThreshold: Math.max(0, Number(event.target.value)) } }))} className="h-9 w-24 rounded-lg border bg-[#fffdf8] px-2 text-center" /></td><td className="p-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${out ? "bg-[#fde8e3] text-[#a83a23]" : low ? "bg-[#f7ead3] text-[#80521a]" : "bg-[#e5f3df] text-[#37711d]"}`}>{out ? "نفد" : low ? "كمية منخفضة" : "متوفر"}</span></td><td className="p-3"><button disabled={update.isPending} onClick={() => update.mutate({ id: product.id, ...draft })} className="inline-flex items-center gap-1 rounded-lg bg-[#5e3508] px-3 py-2 text-xs font-bold text-[#f6cd70] disabled:opacity-60"><Save size={14} />حفظ</button></td></tr>; })}{!products.length && <tr><td colSpan={5} className="p-8 text-center text-[#806743]">لا توجد منتجات بعد.</td></tr>}</tbody></table></div></div></section>;
}
