import { StoreShell } from "@/components/StoreShell";
import { formatPrice, orderStatusHint, orderStatusLabel, ORDER_STATUS_TONES } from "@/lib/store";
import { trpc } from "@/lib/trpc";
import { ClipboardCheck, Search } from "lucide-react";
import { useState } from "react";

export default function OrderTracking() {
  const params = new URLSearchParams(window.location.search);
  const [orderNumber, setOrderNumber] = useState(() => params.get("order") || "");
  const [phone, setPhone] = useState(() => params.get("phone") || "");
  const [lookup, setLookup] = useState<{ orderNumber: string; phone: string } | null>(null);
  const { data, isFetching } = trpc.orders.track.useQuery(lookup || { orderNumber: "غير_صالح", phone: "0" }, { enabled: Boolean(lookup) });
  return <StoreShell><main className="container max-w-3xl py-12 sm:py-18"><div className="rounded-[2rem] border border-[#ead8b3] bg-[#fffdf8] p-6 shadow-[0_16px_40px_rgba(86,50,9,.08)] sm:p-9"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#5e3508] text-[#f6cd70]"><ClipboardCheck /></span><div><p className="text-xs font-bold text-[#a45c08]">خدمة ما بعد الطلب</p><h1 className="font-display text-4xl text-[#5e3508]">تتبع حالة طلبك</h1></div></div><p className="mt-4 text-sm leading-7 text-[#806743]">أدخل رقم الطلب ورقم الهاتف اللذين استخدمتهما عند الطلب. لا يمكن رؤية أي طلبات تخص عملاء آخرين.</p><form onSubmit={event => { event.preventDefault(); setLookup({ orderNumber, phone }); }} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-[#6c4a1d]">رقم الطلب<input required value={orderNumber} onChange={event => setOrderNumber(event.target.value)} placeholder="MS-..." className="mt-2 h-11 w-full rounded-xl border border-[#dfc28c] bg-white px-3 text-sm font-normal outline-none focus:border-[#a45c08]" /></label><label className="text-xs font-bold text-[#6c4a1d]">رقم الهاتف<input required value={phone} onChange={event => setPhone(event.target.value)} inputMode="tel" className="mt-2 h-11 w-full rounded-xl border border-[#dfc28c] bg-white px-3 text-sm font-normal outline-none focus:border-[#a45c08]" /></label><button disabled={isFetching} className="sm:col-span-2 inline-flex items-center justify-center gap-2 rounded-xl bg-[#b66d08] px-4 py-3 text-sm font-bold text-white disabled:opacity-60"><Search size={17} />{isFetching ? "جاري البحث…" : "عرض حالة الطلب"}</button></form>{lookup && !isFetching && data && (data.found ? <section className="mt-7 rounded-2xl border border-[#d7b56d] bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs text-[#806743]">{data.orderNumber}</p><h2 className="mt-1 font-display text-3xl text-[#5e3508]">{orderStatusLabel(data.status)}</h2></div><span className={`rounded-full px-3 py-2 text-xs font-bold ${ORDER_STATUS_TONES[data.status]}`}>{orderStatusLabel(data.status)}</span></div><p className="mt-4 rounded-2xl bg-[#f9edda] p-3 text-xs leading-6 text-[#6c4a1d]">{orderStatusHint(data.status)}</p><div className="mt-5 space-y-2 border-t border-[#f1e5cf] pt-4 text-sm text-[#765a35]">{data.items.map(item => <p key={`${item.productId}-${item.option.label}`}>{item.name} · {item.option.label} × {item.quantity}</p>)}<p className="pt-2 font-bold text-[#a45c08]">الإجمالي: {formatPrice(data.total)}</p></div></section> : <div className="mt-7 rounded-2xl bg-[#fde8e3] p-4 text-sm text-[#9a3d28]">لم نعثر على طلب يطابق هذه البيانات. تأكد من رقم الطلب والهاتف أو تواصل معنا عبر واتساب.</div>)}</div></main></StoreShell>;
}
